### ISSUE TITLE
python run.py遇到报错

### ISSUE THREAD

**Issue by kenbio216** [Water2sea/TPGN#3]
用anaconda用命令“conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge”安装了torchV1.10.1后，把numpy的版本也改成了1.22.4，也安装了1.3.4的pandas库，但是在运行命令“python run.py --model TPGN --data_path ETTh1.csv --root_path ./Datasets/ --batch_size 32 --train_epochs 25 --learning_rate 0.001 --use_gpu True --gpu 0 
”的时候还是报错了。
报错信息：
(pythonFXdemo5) G:\win_code_git\alist_ACTIVITY\pythonFXdemo5>python run.py --model TPGN --data_path ETTh1.csv --root_path ./Datasets/ --batch_size 32 --train_epochs 25 --learning_rate 0.001 --use_gpu True --gpu 0 
Traceback (most recent call last):
  File "G:\win_code_git\alist_ACTIVITY\pythonFXdemo5\run.py", line 4, in <module>
    from exp.exp_main import Exp_Main
  File "G:\win_code_git\alist_ACTIVITY\pythonFXdemo5\exp\exp_main.py", line 10, in <module>
    from models import TPGN, iTransformer, FITS, PDF, TimeMixer, ModernTCN, \
  File "G:\win_code_git\alist_ACTIVITY\pythonFXdemo5\models\iTransformer.py", line 5, in <module>
    from layers.iTransformer_SelfAttention_Family import FullAttention, AttentionLayer
  File "G:\win_code_git\alist_ACTIVITY\pythonFXdemo5\layers\iTransformer_SelfAttention_Family.py", line 6, in <module>
    from reformer_pytorch import LSHSelfAttention
  File "H:\KY_ENV\Anaconda\envs\pythonFXdemo5\lib\site-packages\reformer_pytorch\__init__.py", line 1, in <module>
    from reformer_pytorch.reformer_pytorch import LSHAttention, LSHSelfAttention, Reformer, ReformerLM
  File "H:\KY_ENV\Anaconda\envs\pythonFXdemo5\lib\site-packages\reformer_pytorch\reformer_pytorch.py", line 11, in <module>
    from local_attention import LocalAttention
  File "H:\KY_ENV\Anaconda\envs\pythonFXdemo5\lib\site-packages\local_attention\__init__.py", line 1, in <module>
    from local_attention.local_attention import LocalAttention
  File "H:\KY_ENV\Anaconda\envs\pythonFXdemo5\lib\site-packages\local_attention\local_attention.py", line 10, in <module>
    from local_attention.rotary import SinusoidalEmbeddings, apply_rotary_pos_emb
  File "H:\KY_ENV\Anaconda\envs\pythonFXdemo5\lib\site-packages\local_attention\rotary.py", line 4, in <module>
    from torch.amp import autocast
ModuleNotFoundError: No module named 'torch.amp'

看上去是torch库的问题，已经重装了好几遍了，还是这样，为什么？

**Comment by Water2sea** [comment]
非常感谢您对我们工作的关注。我们目前并未遇到过这个问题，因此可能无法提供太多经验支持。根据您提供的错误提示，建议您是不是可以考虑检查一下amp的使用方法，希望以上内容能够对您有所帮助。
